<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Latent</RootNamespace>
    <AssemblyName>LatentPlugin</AssemblyName>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="8.0.23304.9001" />
    <PackageReference Include="Eto.Forms" Version="2.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Eto">
      <HintPath>$(RhinoSystemDir)\Eto.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rhino.UI">
      <HintPath>$(RhinoSystemDir)\Rhino.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
